# Generated by Django 4.2.9 on 2026-03-05 17:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_task_expected_hours'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('work_description', models.TextField(blank=True, help_text='Brief summary of work completed today')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked (e.g. 8.5)', max_digits=4)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='employees.employee')),
                ('tasks_assigned', models.ManyToManyField(blank=True, help_text='Tasks the employee was working on today', related_name='assigned_in_logs', to='tasks.task')),
                ('tasks_blocked', models.ManyToManyField(blank=True, help_text='Tasks that are blocked and why', related_name='blocked_in_logs', to='tasks.task')),
                ('tasks_completed', models.ManyToManyField(blank=True, help_text='Tasks the employee completed today', related_name='completed_in_logs', to='tasks.task')),
            ],
            options={
                'db_table': 'daily_work_logs',
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
