# Generated by Django 4.2.9 on 2026-03-10 16:15

import apps.daily_reports.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('tasks_assigned', models.TextField(help_text='Summary of tasks assigned today')),
                ('tasks_completed', models.TextField(help_text='Summary of tasks completed today')),
                ('tasks_pending', models.TextField(blank=True, help_text='Summary of tasks still pending')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=4)),
                ('work_description', models.TextField(help_text='Detailed description of work done')),
                ('blockers', models.TextField(blank=True, help_text='Any blockers or issues faced')),
                ('attachment', models.FileField(blank=True, help_text='Optional supporting document', null=True, upload_to=apps.daily_reports.models.daily_report_attachment_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_daily_reports', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Report',
                'verbose_name_plural': 'Daily Reports',
                'ordering': ['-report_date', '-created_at'],
                'unique_together': {('employee', 'report_date')},
            },
        ),
    ]
