# Generated by Django 4.2.9 on 2026-03-23 08:20

import apps.daily_reports.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.daily_reports.models.daily_report_attachment_path)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='daily_reports.dailyreport')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
