# Generated by Django 4.2.9 on 2026-04-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0002_dailyreportattachment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set(),
        ),
    ]
