# Generated by Django 4.2.9 on 2026-04-09 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0004_alter_candidate_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebankdetails',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bank_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.CreateModel(
            name='BankDetailsChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_type', models.CharField(default='updated', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('bank_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='hr.employeebankdetails')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_details_change_log',
                'ordering': ['-changed_at'],
            },
        ),
    ]
