# Generated by Django 4.2.9 on 2026-04-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employeebankdetails_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
