# Generated by Django 4.2.9 on 2026-04-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_add_payslip_is_auto_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebankdetails',
            name='passbook_photo',
            field=models.ImageField(blank=True, null=True, upload_to='bank_details/passbooks/'),
        ),
    ]
