# Generated by Django 4.2.9 on 2026-03-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpresence',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('idle', 'Idle'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
