# Generated by Django 4.2.9 on 2026-03-23 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
        ('attendance', '0002_add_idle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='is_regularized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('overtime', 'Overtime')], default='present', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('total_on_time', models.PositiveIntegerField(default=0)),
                ('total_late', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_streak', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRegularization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('req_type', models.CharField(choices=[('forgot_checkin', 'Forgot to Check-in'), ('forgot_checkout', 'Forgot to Check-out'), ('wrong_time', 'Wrong Time Recorded'), ('absent_but_present', 'Was Present (marked absent)'), ('other', 'Other')], default='other', max_length=30)),
                ('reason', models.TextField()),
                ('requested_login_time', models.TimeField(blank=True, null=True)),
                ('requested_logout_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularizations', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_regularizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
