# Generated by Django 4.2.9 on 2026-03-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='android', max_length=20)),
                ('version_name', models.CharField(max_length=20)),
                ('version_code', models.IntegerField()),
                ('release_notes', models.TextField(blank=True)),
                ('force_update', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_versions',
                'ordering': ['-version_code'],
                'get_latest_by': 'version_code',
            },
        ),
    ]
