# Generated by Django 4.2.9 on 2026-03-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expected_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours required to complete this task', max_digits=5, null=True),
        ),
    ]
