# Generated by Django 4.2.9 on 2026-03-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('logged_in', 'Logged In'), ('logged_out', 'Logged Out'), ('task_created', 'Task Created'), ('task_started', 'Task Started'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('task_assigned', 'Task Assigned'), ('task_delayed', 'Task Delayed'), ('task_cancelled', 'Task Cancelled'), ('employee_added', 'Employee Added'), ('employee_updated', 'Employee Updated'), ('employee_deleted', 'Employee Deleted'), ('updated_profile', 'Updated Profile'), ('created_user', 'Created User'), ('progress_updated', 'Progress Updated'), ('comment_added', 'Comment Added')], max_length=50)),
                ('description', models.TextField()),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
