# Generated by Django 4.2.9 on 2026-03-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='verb',
            field=models.CharField(choices=[('logged_in', 'Logged In'), ('logged_out', 'Logged Out'), ('task_created', 'Task Created'), ('task_started', 'Task Started'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('task_assigned', 'Task Assigned'), ('task_delayed', 'Task Delayed'), ('task_cancelled', 'Task Cancelled'), ('employee_added', 'Employee Added'), ('employee_updated', 'Employee Updated'), ('employee_deleted', 'Employee Deleted'), ('updated_profile', 'Updated Profile'), ('created_user', 'Created User'), ('progress_updated', 'Progress Updated'), ('comment_added', 'Comment Added'), ('page_visited', 'Page Visited'), ('file_uploaded', 'File Uploaded'), ('document_downloaded', 'Document Downloaded'), ('daily_report_submitted', 'Daily Report Submitted'), ('timer_started', 'Timer Started'), ('timer_stopped', 'Timer Stopped'), ('salary_structure_created', 'Salary Structure Created'), ('salary_updated', 'Salary Updated'), ('bank_details_updated', 'Bank Details Updated'), ('salary_payment_created', 'Salary Payment Created'), ('salary_paid', 'Salary Paid'), ('payslip_generated', 'Payslip Generated')], max_length=50),
        ),
    ]
