# Generated by Django 4.2.9 on 2026-03-09 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('agent_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remote_agent', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('ended', 'Ended')], default='pending', max_length=20)),
                ('fps', models.IntegerField(default=2)),
                ('quality', models.IntegerField(default=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='remote_control.remoteagent')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
